<?php
/**
 * Load the data file
 */
function loadData($file) {
    $DATAString = file_get_contents($file);
    return json_decode($DATAString, true);
}

/**
 * Print the status from the server query
 */
function printServerStatus($status){
    $online = (array_key_exists('gametype', $status)) ? true : false;
    
    if ($online) {
        $numPlayers = count($status['players']);
        $maxPlayers = $status['maxplayers'];
        $motd       = $status['motd'];
        $version    = $status['version'];
    } else {
        $numPlayers = '';
        $maxPlayers = '';
        $motd       = '';
        $version    = '';
    }
    
    echo "<ul class='status'>";
    if   ($online) echo "<li class='status-online'>online</li>";
    else           echo "<li class='status-offline'>offline</li>";
    
    echo "<li><span class='status-field'>players:</span><span class='status-value'>" . $numPlayers . "/" . $maxPlayers . "</span></li>";
    echo "<li><span class='status-field'>MOTD:</span><span class='status-value'>" . $motd . "</span></li>";
    echo "<li><span class='status-field'>Version:</span><span class='status-value'>" . $version . "</span></li>";
    echo "</ul>";
}

/**
 * Print the list of players logged in
 */
function printPlayerList($status) {
    $online = (array_key_exists('gametype', $status)) ? true : false;
    if ($online) {
        echo "<ul class='player-list'>";
        foreach ($status['players'] as $player) {
            echo "<li><span class='player'>" . $player . "</span></li>";
            
        }
        echo "</ul>";
    }
    
}

/**
 * Print the MOTD
 */
function printServerMOTD($id) {
    $data = getServerStatus($id);
    echo $data['motd'];
}


/*****************************************************************************\
| SETUP                                                                        |
\*****************************************************************************/

// Load the data file (this is generated by the mcpoll.py script
$DATA = loadData("/srv/crafter.lapinlabs.com/data/servers.json");

$PAGE_TITLE = "lapinlabs.com Minecraft Server";

$INTRO = "lapinlabs.com hosts mutliple minecraft servers. Each one uses whitelisting so if you'd like to join please <a href=\"mailto:crempp@gmail.com\">email me</a>.";

?>
<html>
  <head>
    <title><?php echo $PAGE_TITLE; ?></title>
    <link href='http://fonts.googleapis.com/css?family=Signika+Negative:400,700' rel='stylesheet' type='text/css'>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="style.css" />
  </head>
  <body>
    <div class='container'>
        <h1><?php echo $PAGE_TITLE; ?></h1>
        <div class='summary'>
            <p><?php echo $INTRO; ?></p>
        </div>
        <div class='summary'>
            
        </div>
      
        <table class='server-table'>
          <thead>
              <tr>
                <th>Host</th>
                <th>Status</th>
                <th>Players</th>
                <th>Description</th>
                <th>Settings</th>
              </tr>
          </thead>
          <tbody>
            <?php foreach($DATA['servers'] as $server) { ?>
            
            <tr>
              <td><?php echo $server['host']; ?>:<?php echo $server['config']['server-port']; ?></td>
              <td><?php printServerStatus($server['status']); ?></td>
              <td><?php printPlayerList($server['status']); ?></td>
              <td>
                <div class='server-title'>
                  <a href="<?php echo $server['map']['map-url']; ?>" target="_blank"><i class="fa fa-globe"></i></a>
                  <?php echo $server['name']; ?>
                </div>
                <p><?php echo $server['description'] ?></p>
              </td>
              <td>
                <ul class='setting-list'>
                  <li><span class='setting-field'>level-type</span><span class='setting-value'><?php echo $server['config']['level-type']; ?></span></li>
                  <li><span class='setting-field'>difficulty=</span><span class='setting-value'><?php echo $server['config']['difficulty']; ?></span></li>
                  <li><span class='setting-field'>enable-command-block</span><span class='setting-value'><?php echo $server['config']['enable-command-block']; ?></span></li>
                  <li><span class='setting-field'>gamemode</span><span class='setting-value'><?php echo $server['config']['gamemode']; ?></span></li>
                  <li><span class='setting-field'>max-players</span><span class='setting-value'><?php echo $server['config']['max-players'] ?></span></li>
                </ul>
              </td>
            </tr>
            <?php } ?>
          </tbody>
      
        </table>
    </div>  
  </body>
</html>
